USE quiz_app;

-- Create 100 users with proper names and a decent password
INSERT INTO users (username, password) VALUES
('aarav_mehra', 'Secure@123'),
('isha_kapoor', 'Secure@123'),
('vihaan_verma', 'Secure@123'),
('anaya_sharma', 'Secure@123'),
('arjun_gupta', 'Secure@123'),
('siya_singh', 'Secure@123'),
('kabir_malhotra', 'Secure@123'),
('meera_patel', 'Secure@123'),
('reyansh_rana', 'Secure@123'),
('tanya_das', 'Secure@123'),
('advait_kumar', 'Secure@123'),
('prisha_iyer', 'Secure@123'),
('rudra_chauhan', 'Secure@123'),
('kiara_nair', 'Secure@123'),
('aarush_saxena', 'Secure@123'),
('myra_mishra', 'Secure@123'),
('samar_bhatt', 'Secure@123'),
('riya_seth', 'Secure@123'),
('krishna_yadav', 'Secure@123'),
('lavanya_jain', 'Secure@123'),
('dhruv_rao', 'Secure@123'),
('anika_bose', 'Secure@123'),
('arush_shah', 'Secure@123'),
('isha_dave', 'Secure@123'),
('veer_singhania', 'Secure@123'),
('saanvi_trivedi', 'Secure@123'),
('ayush_goel', 'Secure@123'),
('anvi_pandey', 'Secure@123'),
('omkar_rathi', 'Secure@123'),
('zoya_dhar', 'Secure@123'),
('vivaan_kohli', 'Secure@123'),
('avani_rastogi', 'Secure@123'),
('tanmay_agarwal', 'Secure@123'),
('isha_qureshi', 'Secure@123'),
('parth_saini', 'Secure@123'),
('kriti_lal', 'Secure@123'),
('yash_chopra', 'Secure@123'),
('aanya_khan', 'Secure@123'),
('devansh_nath', 'Secure@123'),
('sakshi_paul', 'Secure@123'),
('harsh_kulkarni', 'Secure@123'),
('vanya_siddiqui', 'Secure@123'),
('manan_raghav', 'Secure@123'),
('nitya_reddy', 'Secure@123'),
('vivan_iyengar', 'Secure@123'),
('shruti_nambiar', 'Secure@123'),
('ronit_joshi', 'Secure@123'),
('aisha_mallick', 'Secure@123'),
('aryan_tiwari', 'Secure@123'),
('mira_fernandes', 'Secure@123'),
('aadi_shetty', 'Secure@123'),
('mahi_parekh', 'Secure@123'),
('arav_salian', 'Secure@123'),
('tisha_varma', 'Secure@123'),
('rehaan_suri', 'Secure@123'),
('diya_sawant', 'Secure@123'),
('vihaan_chopra', 'Secure@123'),
('anaya_shinde', 'Secure@123'),
('rohan_samant', 'Secure@123'),
('shreya_poddar', 'Secure@123'),
('nishant_bora', 'Secure@123'),
('rhea_kamble', 'Secure@123'),
('arjit_goswami', 'Secure@123'),
('isha_banerjee', 'Secure@123'),
('kian_thakur', 'Secure@123'),
('sana_joshi', 'Secure@123'),
('dev_shastri', 'Secure@123'),
('aaliyah_rizvi', 'Secure@123'),
('harshit_jadeja', 'Secure@123'),
('tara_sengupta', 'Secure@123'),
('aryan_mahajan', 'Secure@123'),
('shraddha_puri', 'Secure@123'),
('neel_shukla', 'Secure@123'),
('simran_joshi', 'Secure@123'),
('aditya_kaur', 'Secure@123'),
('palak_mehta', 'Secure@123'),
('raj_kashyap', 'Secure@123'),
('sanya_mukherjee', 'Secure@123'),
('vedant_bajpai', 'Secure@123'),
('isha_jaiswal', 'Secure@123'),
('laksh_grover', 'Secure@123'),
('nimrat_kapoor', 'Secure@123'),
('mihir_gandhi', 'Secure@123'),
('anvi_kamble', 'Secure@123'),
('arham_khan', 'Secure@123'),
('shruti_raina', 'Secure@123'),
('ayansh_bhardwaj', 'Secure@123'),
('kavya_malhotra', 'Secure@123'),
('karan_nanda', 'Secure@123'),
('suhana_yusuf', 'Secure@123'),
('reyansh_puri', 'Secure@123'),
('avni_makhija', 'Secure@123'),
('ranbir_saxena', 'Secure@123'),
('mehul_nayak', 'Secure@123'),
('sanjana_malik', 'Secure@123'),
('ishaan_mitra', 'Secure@123'),
('pranav_kapadia', 'Secure@123'),
('kanika_saran', 'Secure@123'),
('yuvraj_rastogi', 'Secure@123'),
('tanishq_mohanty', 'Secure@123'),
('prisha_vaidya', 'Secure@123'),
('rahul_dewan', 'Secure@123'),
('radhika_bedi', 'Secure@123');


-- Insert 50 quiz attempts
INSERT INTO attempts (username, quiz, score) VALUES
('aarav_mehra', 'DBMS', 8),
('isha_kapoor', 'PYTHON', 7),
('vihaan_verma', 'JAVA', 5),
('anaya_sharma', 'DBMS', 9),
('arjun_gupta', 'PYTHON', 3),
('siya_singh', 'JAVA', 6),
('kabir_malhotra', 'DBMS', 10),
('meera_patel', 'JAVA', 8),
('reyansh_rana', 'PYTHON', 6),
('tanya_das', 'DBMS', 5),
('advait_kumar', 'PYTHON', 4),
('prisha_iyer', 'JAVA', 9),
('rudra_chauhan', 'DBMS', 6),
('kiara_nair', 'PYTHON', 7),
('aarush_saxena', 'JAVA', 3),
('myra_mishra', 'PYTHON', 10),
('samar_bhatt', 'JAVA', 5),
('riya_seth', 'DBMS', 7),
('krishna_yadav', 'PYTHON', 2),
('lavanya_jain', 'JAVA', 6),
('dhruv_rao', 'DBMS', 9),
('anika_bose', 'JAVA', 8),
('arush_shah', 'PYTHON', 5),
('isha_dave', 'JAVA', 4),
('veer_singhania', 'DBMS', 10),
('saanvi_trivedi', 'PYTHON', 3),
('ayush_goel', 'JAVA', 6),
('anvi_pandey', 'DBMS', 8),
('omkar_rathi', 'PYTHON', 4),
('zoya_dhar', 'JAVA', 7),
('vivaan_kohli', 'PYTHON', 9),
('avani_rastogi', 'DBMS', 6),
('tanmay_agarwal', 'JAVA', 2),
('isha_qureshi', 'PYTHON', 5),
('parth_saini', 'JAVA', 9),
('kriti_lal', 'DBMS', 3),
('yash_chopra', 'PYTHON', 8),
('aanya_khan', 'JAVA', 4),
('devansh_nath', 'DBMS', 7),
('sakshi_paul', 'PYTHON', 6),
('harsh_kulkarni', 'JAVA', 5),
('vanya_siddiqui', 'DBMS', 9),
('manan_raghav', 'PYTHON', 4),
('nitya_reddy', 'JAVA', 6),
('vivan_iyengar', 'DBMS', 10),
('shruti_nambiar', 'PYTHON', 2),
('ronit_joshi', 'JAVA', 3),
('aisha_mallick', 'PYTHON', 7),
('aryan_tiwari', 'JAVA', 4),
('mira_fernandes', 'DBMS', 8);